import numpy as np
x = np.prod([1.,2.])
print(x)
x = np.prod([[1.,2.],[3.,4.]])
print(x)
x = np.prod([1.,2.], dtype= np.int32)
print(int(x))
x = np.prod([1.,2.], None, np.int32)
print(int(x))
x = np.prod([1.,2.], None, dtype= np.int32)
print(int(x))
x = np.prod(dtype= np.int32, a=[1.,2.])
print(int(x))
x = np.prod([[1.,2.],[3.,4.]], axis=0)
print(list(x))
x = np.prod([[1.,2.],[3.,4.]], axis=1)
print(list(x))
x = np.prod([3.,4.], keepdims=True)
print(list(x))
a = [3.,4.]
x = np.prod(a, dtype= np.int32)
print(int(x))
